// <auto-generated />
using System;
using Combo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Combo.Migrations
{
    [DbContext(typeof(ComboContext))]
    [Migration("20240407040150_Waybills")]
    partial class Waybills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Combo.Database.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoxCount")
                        .HasColumnType("integer");

                    b.Property<int>("PalleteCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Combo.Database.Models.Waybill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActualCargoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DeclaredCargoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActualCargoId");

                    b.HasIndex("DeclaredCargoId");

                    b.ToTable("Waybill");
                });

            modelBuilder.Entity("Combo.Database.Models.Waybill", b =>
                {
                    b.HasOne("Combo.Database.Models.Cargo", "ActualCargo")
                        .WithMany()
                        .HasForeignKey("ActualCargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Combo.Database.Models.Cargo", "DeclaredCargo")
                        .WithMany()
                        .HasForeignKey("DeclaredCargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualCargo");

                    b.Navigation("DeclaredCargo");
                });
#pragma warning restore 612, 618
        }
    }
}
