@Combo_HostAddress = http://localhost:5113

GET {{Combo_HostAddress}}/Waybill
Accept: application/json

###

GET {{Combo_HostAddress}}/Trailer/22345200-abe8-4f60-90c8-0d43c5f6c0f6
Accept: application/json

###

POST {{Combo_HostAddress}}/Truck
Accept: application/json
